apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: svc-http-echo
  namespace: argocd
spec:
  project: test
  sources:
    # 1️⃣ Base chart repo — no values.yaml here
    - repoURL: https://github.com/Smitty-0881/helm-charts.git
      targetRevision: main
      path: svc-http-echo

    # 2️⃣ Environment repo — defines which values.yaml overrides apply
    - repoURL: https://github.com/Smitty-0881/env-microk8s2.git
      targetRevision: main
      path: apps/svc-http-echo
      helm:
        valueFiles:
          - values.yaml
  destination:
    server: https://192.168.4.96:16443
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
