apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: svc-http-echo
  namespace: argocd
spec:
  project: test
  source:
    repoURL: https://github.com/Smitty-0881/helm-charts.git
    targetRevision: main
    path: svc-http-echo
    helm:
      valueFiles:
        - $values/env-microk8s2/apps/svc-http-echo/values.yaml
      valuesFrom:
        - repoURL: https://github.com/Smitty-0881/env-microk8s2.git
          targetRevision: main
          ref: values
  destination:
    server: https://192.168.4.96:16443
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
