apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microk8s2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Smitty-0881/env-microk8s2.git
    targetRevision: main
    path: apps
  destination:
    server: https://192.168.4.96:16443
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
